# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0004_auto_20170602_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_image_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
